#!/bin/sh

set -e -x

scripts_folder=$(dirname $0)

# Install certstrap
# go get -v github.com/square/certstrap

# Place keys and certificates here
# depot_path="etcd-certs"
depot_path=${dir_cf_certs}/"etcd-certs"
mkdir -p ${depot_path}

# CA to distribute to etcd clients and servers
#### ${scripts_folder}/generate_ca_cert --common-name "etcdCA" --depot-path ${depot_path} --output-file etcd-ca
certstrap --depot-path "${depot_path}" init --passphrase '' --common-name "etcdCA"
mv -f "${depot_path}/etcdCA.crt" "${depot_path}/etcd-ca.crt"
mv -f "${depot_path}/etcdCA.key" "${depot_path}/etcd-ca.key"
mv -f "${depot_path}/etcdCA.crl" "${depot_path}/etcd-ca.crl"

# Server certificate to share across the etcd cluster
server_cn="cf-etcd.service.cf.internal"
####${scripts_folder}/generate_end_entity_certs --common-name "cf-etcd.service.cf.internal" --ca-name etcd-ca --domain '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal' --depot-path ${depot_path} --output-file server
certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name "${server_cn}" --domain '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal'
certstrap --depot-path "${depot_path}" sign "${server_cn}" --CA "etcd-ca"
mv -f "${depot_path}/${server_cn}.key" "${depot_path}/server.key"
mv -f "${depot_path}/${server_cn}.csr" "${depot_path}/server.csr"
mv -f "${depot_path}/${server_cn}.crt" "${depot_path}/server.crt"

# Client certificate to distribute to jobs that access etcd
####${scripts_folder}/generate_end_entity_certs --common-name "clientName" --ca-name etcd-ca --depot-path ${depot_path} --output-file client
certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name "clientName"
certstrap --depot-path "${depot_path}" sign "clientName" --CA "etcd-ca"
mv -f "${depot_path}/clientName.key" "${depot_path}/client.key"
mv -f "${depot_path}/clientName.csr" "${depot_path}/client.csr"
mv -f "${depot_path}/clientName.crt" "${depot_path}/client.crt"

# CA to distribute across etcd peers
####${scripts_folder}/generate_ca_cert --common-name "peerCA" --depot-path ${depot_path} --output-file peer-ca
certstrap --depot-path "${depot_path}" init --passphrase '' --common-name "peerCA"
mv -f "${depot_path}/peerCA.crt" "${depot_path}/peer-ca.crt"
mv -f "${depot_path}/peerCA.key" "${depot_path}/peer-ca.key"
mv -f "${depot_path}/peerCA.crl" "${depot_path}/peer-ca.crl"

# Client certificate to distribute across etcd peers
server_cn2="cf-etcd.service.cf.internal"
####${scripts_folder}/generate_end_entity_certs --common-name cf-etcd.service.cf.internal --domain '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal' --ca-name peer-ca --depot-path ${depot_path} --output-file peer
certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name "${server_cn2}" --domain '*.cf-etcd.service.cf.internal,cf-etcd.service.cf.internal'
certstrap --depot-path "${depot_path}" sign "${server_cn2}" --CA "peer-ca"
mv -f "${depot_path}/${server_cn2}.key" "${depot_path}/peer.key"
mv -f "${depot_path}/${server_cn2}.csr" "${depot_path}/peer.csr"
mv -f "${depot_path}/${server_cn2}.crt" "${depot_path}/peer.crt"