#!/bin/bash

set -e -x

# scripts_folder=$(dirname $0)

# Install certstrap
# go get -v github.com/square/certstrap

# Place keys and certificates here
depot_path=${dir_cf_certs}/"uaa-certs"
mkdir -p ${depot_path}

# CA to generate client certs
#### ${scripts_folder}/generate_ca_cert --common-name "cert-authority" --depot-path ${depot_path} --output-file server-ca
certstrap --depot-path "${depot_path}" init --passphrase '' --common-name "cert-authority"
mv -f "${depot_path}/cert-authority.crt" "${depot_path}/server-ca.crt"
mv -f "${depot_path}/cert-authority.key" "${depot_path}/server-ca.key"
mv -f "${depot_path}/cert-authority.crl" "${depot_path}/server-ca.crl"

# Certificate to use as the client
server_cn="uaa.service.cf.internal"
#### ${scripts_folder}/generate_end_entity_certs --common-name ${server_cn} --ca-name server-ca --depot-path ${depot_path} --output-file server
certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name "${server_cn}"
certstrap --depot-path "${depot_path}" sign "${server_cn}" --CA "server-ca"
mv -f "${depot_path}/${server_cn}.key" "${depot_path}/server.key"
mv -f "${depot_path}/${server_cn}.csr" "${depot_path}/server.csr"
mv -f "${depot_path}/${server_cn}.crt" "${depot_path}/server.crt"