#!/bin/sh

set -e -x

# scripts_folder=$(dirname $0)

# Install certstrap
# go get -v github.com/square/certstrap

# Place keys and certificates here
# depot_path="consul-certs"
depot_path=${dir_cf_certs}/"consul-certs"
mkdir -p ${depot_path}

####${scripts_folder}/generate_ca_cert --common-name "consulCA" --depot-path ${depot_path} --output-file server-ca
certstrap --depot-path "${depot_path}" init --passphrase '' --common-name "consulCA"
mv -f "${depot_path}/consulCA.crt" "${depot_path}/server-ca.crt"
mv -f "${depot_path}/consulCA.key" "${depot_path}/server-ca.key"
mv -f "${depot_path}/consulCA.crl" "${depot_path}/server-ca.crl"

# Server certificate to share across the consul cluster
server_cn=server.dc1.cf.internal
#####${scripts_folder}/generate_end_entity_certs --common-name server.dc1.cf.internal --ca-name server-ca --depot-path ${depot_path} --output-file server
certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name "${server_cn}"
certstrap --depot-path "${depot_path}" sign "${server_cn}" --CA "server-ca"
mv -f "${depot_path}/${server_cn}.key" "${depot_path}/server.key"
mv -f "${depot_path}/${server_cn}.csr" "${depot_path}/server.csr"
mv -f "${depot_path}/${server_cn}.crt" "${depot_path}/server.crt"

# Agent certificate to distribute to jobs that access consul
####${scripts_folder}/generate_end_entity_certs --common-name 'consul agent' --ca-name server-ca --depot-path ${depot_path} --output-file agent
certstrap --depot-path "${depot_path}" request-cert --passphrase '' --common-name "consul_agent"
certstrap --depot-path "${depot_path}" sign "consul agent" --CA "server-ca"
mv -f "${depot_path}/consul_agent.key" "${depot_path}/agent.key"
mv -f "${depot_path}/consul_agent.csr" "${depot_path}/agent.csr"
mv -f "${depot_path}/consul_agent.crt" "${depot_path}/agent.crt"

# Encrypt key
cat /dev/urandom | head -c 16 | base64 > ${depot_path}/encrypt_key