meta: ~

jobs:
#network [0]
  - name: nats_z1
    instances: (( meta.nats-z1-instances || 1 ))

  - name: stats_z1
    instances: (( meta.stats-z1-instances || 1 ))

  - name: blobstore_z1
    instances: (( meta.blobstore-z1-instances || 1 ))

  - name: postgres_z1
    instances: (( meta.postgres-z1-instances || 1 ))

  - name: uaa_z1
    instances: (( meta.uaa-z1-instances || 1 ))

  - name: api_z1
    instances: (( meta.uaa-z1-instances || 1 ))

  - name: clock_global
    instances: (( meta.clock-global-z1-instances || 1 ))

  - name: api_worker_z1
    instances: (( meta.api-worker-z1-instances || 1 ))

  - name: router_z1
    instances: (( meta.router-z1-instances || 1 ))

  - name: loggregator_z1
    instances: (( merge || 0 ))

  - name: doppler_z1
    instances: (( merge || meta.doppler-z1-instances || 1 ))

  - name: loggregator_trafficcontroller_z1
    instances: (( meta.loggregator-trafficcontroller-z1-instances || 1 ))

  - name: etcd_z1
    instances: (( meta.etcd-z1-instances || 1 ))

  - name: consul_z1
    instances: (( meta.consul-z1-instances || 1 ))

  - name: hm9000_z1
    instances: (( meta.hm9000-z1-instances || 1 ))

  - name: runner_z1
    instances: (( meta.runner-z1-instances || 1 ))

#network [1]
  - name: nats_z2
    instances: (( meta.nats-z2-instances || 0 ))

  - name: router_z2
    instances: (( meta.router-z2-instances || 0 ))

  - name: etcd_z2
    instances: (( meta.etcd-z2-instances || 0 ))

  - name: consul_z2
    instances: (( meta.consul-z2-instances || 0 ))

  - name: loggregator_z2
    instances: (( meta.loggregator-z2-instances || 0 ))

  - name: doppler_z2
    instances: (( meta.doppler-z2-instances || 0 ))

  - name: loggregator_trafficcontroller_z2
    instances: (( meta.loggregator-trafficcontroller-z2-instances || 0 ))

  - name: uaa_z2
    instances: (( meta.uaa-z2-instances || 0 ))

  - name: api_z2
    instances: (( meta.api-z2-instances || 0 ))

  - name: api_worker_z2
    instances: (( meta.api-worker-z2-instances || 0 ))

  - name: hm9000_z2
    instances: (( meta.hm9000-z2-instances || 0 ))

  - name: runner_z2
    instances: (( meta.runner-z2-instances || 0 ))
